# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.26.2
_src_path: gh:tsvikas/python-template
cli_framework: cyclopts
format_tool: ruff
get_package_version_from_vcs: true
github_user: tsvikas
in_codecov: false
in_pypi: false
in_rtd: false
jupyter_files: forbid
license: MIT
package_description: run the same command for all subdirs.
package_name: run_in_subdirs
project_name: run-in-subdirs
python_min: 10
user_email: tsvikas@gmail.com
user_name: Tsvika Shapira
year: 2026
